# Generated by Django 5.2.3 on 2025-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(default='Option A', max_length=20)),
                ('option2', models.CharField(default='Option A', max_length=20)),
                ('option3', models.CharField(default='Option A', max_length=20)),
            ],
        ),
    ]
