# Generated by Django 5.2.3 on 2025-07-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
